# Build settings
[build]
  # Base directory where commands are run
  base = "Frontend"
  # Directory to publish (output from the build command)
  publish = "dist"
  # Build command
  command = "npm run build"

# Redirects and rewrites
[[redirects]]
  # Redirect all routes to index.html for SPA routing
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for cache control and security
[[headers]]
  # Define headers for all files in the publish directory
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https://images.unsplash.com https://images.pexels.com https://randomuser.me; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; connect-src 'self' https://sportomic-api.example.com http://localhost:5000;"

# Environment variables
[context.production.environment]
  NODE_ENV = "production"
  VITE_API_URL = "https://sportomic-api.example.com/api"

[context.deploy-preview.environment]
  NODE_ENV = "production"
  VITE_API_URL = "https://sportomic-api.example.com/api"
